"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.sequelize.query(
      `ALTER SEQUENCE "Companies_id_seq" RESTART WITH 1`
    );
    await queryInterface.sequelize.query(`DELETE FROM "Companies"`);
    await queryInterface.bulkInsert("Companies", [
      {
        id: 1,
        company_icon: "https://example.com/logo1.png",
        company_name: "PT Example 1",
        description:
          "We are a technology company specializing in web development.",
        location: "Jakarta",
        company_size: "51 - 200 employees",
        email: "info@example1.com",
        whatsapp_number: "+6281234567890",
        working_place: "remote",
        website_url: "https://example1.com",
        created_at: "2021-01-01 00:00:00",
        updated_at: "2021-01-01 00:00:00",
      },
      {
        id: 2,
        company_icon: "https://example.com/logo2.png",
        company_name: "PT Example 2",
        description:
          "We are a software development company that focuses on building mobile apps.",
        location: "Bandung",
        company_size: "11 - 50 employees",
        email: "info@example2.com",
        whatsapp_number: "+6289876543210",
        working_place: "onsite",
        website_url: "https://example2.com",
        created_at: "2021-01-01 00:00:00",
        updated_at: "2021-01-01 00:00:00",
      },
      {
        id: 3,
        company_icon: "https://example.com/logo3.png",
        company_name: "PT Example 3",
        description:
          "We are a design agency that provides branding and creative services.",
        location: "Surabaya",
        company_size: "201 - 500 employees",
        email: "info@example3.com",
        whatsapp_number: "+6281112223333",
        working_place: "hybird",
        website_url: "https://example3.com",
        created_at: "2021-01-01 00:00:00",
        updated_at: "2021-01-01 00:00:00",
      },
      {
        id: 4,
        company_icon: "https://example.com/logo.png",
        company_name: "PT. Example",
        description: "Perusahaan yang bergerak di bidang teknologi informasi",
        location: "Jakarta",
        company_size: "50-100 employees",
        email: "hr@example.com",
        whatsapp_number: "081234567890",
        working_place: "remote",
        website_url: "https://example.com",
        created_at: "2022-05-11 10:00:00",
        updated_at: "2022-05-11 10:00:00",
      },
      {
        id: 5,
        company_icon: "https://example.com/logo2.png",
        company_name: "PT. Contoh",
        description: "Perusahaan yang bergerak di bidang manufaktur",
        location: "Bandung",
        company_size: "100-200 employees",
        email: "hr@contoh.com",
        whatsapp_number: "081234567891",
        working_place: "onsite",
        website_url: "https://contoh.com",
        created_at: "2022-05-12 11:00:00",
        updated_at: "2022-05-12 11:00:00",
      },
      {
        id: 6,
        company_icon: "https://example.com/company1-icon.png",
        company_name: "Company 1",
        description: "This is a description for Company 1",
        location: "Jakarta, Indonesia",
        company_size: "100-200 employees",
        email: "info@company1.com",
        whatsapp_number: "+6281234567890",
        working_place: "onsite",
        website_url: "https://www.company1.com",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 7,
        company_icon: "https://example.com/company2-icon.png",
        company_name: "Company 2",
        description: "This is a description for Company 2",
        location: "Surabaya, Indonesia",
        company_size: "50-100 employees",
        email: "info@company2.com",
        whatsapp_number: "+6289876543210",
        working_place: "remote",
        website_url: "https://www.company2.com",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 8,
        company_icon: "https://example.com/company3-icon.png",
        company_name: "Company 3",
        description: "This is a description for Company 3",
        location: "Bandung, Indonesia",
        company_size: "200-500 employees",
        email: "info@company3.com",
        whatsapp_number: "+6285678901234",
        working_place: "onsite",
        website_url: "https://www.company3.com",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 9,
        company_icon: "https://example.com/company4-icon.png",
        company_name: "Company 4",
        description: "This is a description for Company 4",
        location: "Yogyakarta, Indonesia",
        company_size: "500-1000 employees",
        email: "info@company4.com",
        whatsapp_number: "+6280987654321",
        working_place: "onsite",
        website_url: "https://www.company4.com",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 10,
        company_icon: "https://example.com/company5-icon.png",
        company_name: "Company 5",
        description: "This is a description for Company 5",
        location: "Surabaya, Indonesia",
        company_size: "50-100 employees",
        email: "info@company5.com",
        whatsapp_number: "+6287654321098",
        working_place: "remote",
        website_url: "https://www.company5.com",
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Companies", null, {});
  },
};
